### ISSUE TITLE
Empty space usage to high 

### ISSUE THREAD

**Issue by vogella** [angelozerr/jdt-codemining#2]
See screenshot.

![selection_249](https://user-images.githubusercontent.com/139910/37780665-7b961bee-2def-11e8-9f55-1fe49a033f7b.png)

Tested with Eclipse SDK
Version: Photon (4.8)
Build id: I20180322-0645
OS: Linux, v.4.13.0-36-generic, x86_64 / gtk 3.22.25, WebKit 2.18.6

**Comment by angelozerr** [comment]
@vogella problem is fixed. I had to do that with M6. M7 fixes the problem.

**Comment by vogella** [comment]
I used I build from today. Are you sure this is fixed?

Am 22.03.2018 18:19 schrieb "Angelo" <notifications@github.com>:

**Comment by angelozerr** [comment]
> I used I build from today. Are you sure this is fixed?

I mean that I'm waiting for a fix of https://bugs.eclipse.org/bugs/show_bug.cgi?id=531957 (fixed in M7) to remov eextra space in JDT CodeMining fixed with https://github.com/angelozerr/jdt-codemining/commit/4c7616ac7d4bfa20ebce57d76e98a36a1d098e16 

So please reinstall jdt-codemining, job is done https://opensagres.ci.cloudbees.com/job/jdt-codemining/

**Comment by vogella** [comment]
Yes looks better, thanks!
