### ISSUE TITLE
No command for unit tests but I see a Run command

### ISSUE THREAD

**Issue by vogella** [angelozerr/jdt-codemining#3]
The no command code minining information looks wrong also the empty underline.

![selection_255](https://user-images.githubusercontent.com/139910/37819056-81c1d458-2e7c-11e8-9552-2fc89acb64eb.png)

**Comment by angelozerr** [comment]
* "no command"

The "no command" is because I think you have selected  "Only if there is at least one reference". If you unselect it, you should see "0 references" If https://git.eclipse.org/r/#/c/120005/ is merged, it should not display "no command".

 * Why no run, Why _: I don't know? If you reopen the editor you have the same problem? Coudl you share your class?

 * What is this? : it's the JUnit status (that you have checked in the preferences). If you Run the test, this icon should be updated with an another icon (error or ok).

See following demo:

![](https://github.com/angelozerr/jdt-codemining/raw/master/images/JUnitCodeMiningDemo.gif)

**Comment by vogella** [comment]
Thanks, I believe this can be closed.
