### ISSUE TITLE
Lombok annotations are not showed properly

### ISSUE THREAD

**Issue by Ravisankar-Challa** [angelozerr/jdt-codemining#37]
![image](https://user-images.githubusercontent.com/11788842/41042842-fb231cd6-69e5-11e8-8e39-27ffcafe37e9.png)
Adding a sample project for testing.
https://github.com/Ravisankar-Challa/meecrowave_test/blob/master/src/main/java/meecrowave/model/MiscellaneousInfo.java

Note: Lombok needs to be configured in the eclipse ide 
https://projectlombok.org/downloads/lombok.jar
place the lombok file in the same folder of eclipse.exe file and update the eclipse.ini file 

-vmargs
**_-javaagent:lombok.jar_**
-Dosgi.requiredJavaVersion=1.8

**Comment by angelozerr** [comment]
I have tried to follow your instruction, but I have not the same thing than you:

![image](https://user-images.githubusercontent.com/1932211/41527278-e8057914-72e6-11e8-8aa3-198f663ae9d7.png)

Perhaps it requires to install other plugin like STS?

**Comment by Ravisankar-Challa** [comment]
Those things only show up if we enable 
![image](https://user-images.githubusercontent.com/11788842/41660024-3777f410-74de-11e8-8b39-05442f69a293.png)

**Comment by angelozerr** [comment]
Ok my problem was about config of lombok.jar. I have the same problem than you.

After debugging, it seems that lombok agent update JDT ASTNode to  generate getter, and change @Log annotation with some code.

It causes the problem that you see. I think I have a solution but it will be linked to lombok and it breaks a lot of code -(

I don't know if it's a feature that JDT wishes to support because it will be linked to lombok.

**Comment by vogella** [comment]
One thing to consider is that Lombok violates the APT spec as it modifies the class directly instead of generating new ones. So I assume we will see additional code minings for the generate code once this works.

**Comment by angelozerr** [comment]
@Ravisankar-Challa QI'm sorry, but I think I will not fix this issue. It's to specific to lombok
