### ISSUE TITLE
Possibility to restrict "Show method parameter names" to primitives

### ISSUE THREAD

**Issue by nuessgens** [angelozerr/jdt-codemining#45]
I'd like to have a possiblity to restrict "Show method parameter names" in a way that the names are only displayed on primitives (boolean,int,long...) and strings.

I think mostly by passing complex objects one can derive their meaning from the type.
Assume the following editor-view:
```
File dir = new File(pathname: "/tmp/test/");
doSomething(directory: dir, create: true);
```
The "directory:" parameter-name does not provide any useful additional information but uses a lot of space.
With the suggested feature enabled it would look like:
```
File dir = new File(pathname: "/tmp/test/");
doSomething(dir, create: true);
```

**Comment by angelozerr** [comment]
@vogella what do you think about this feature?

**Comment by vogella** [comment]
+1

**Comment by angelozerr** [comment]
@vogella @nuessgens have you a suggestion for label of this preference?

**Comment by vogella** [comment]
Suggested name: Show parameter names only for primitive types

Angelo <notifications@github.com> schrieb am Mi., 4. Juli 2018, 08:42:

**Comment by nuessgens** [comment]
"Show parameter names only for primitive types" sounds good to me (as long as the implementation includes String-parameters, too ;) )

**Comment by angelozerr** [comment]
@nuessgens @vogella please reinstall JDT CodeMining, now you have a new preference `Show parameter only for literal` which is enabled by default. Here a little demo:

![showparameteronlyforliteral](https://user-images.githubusercontent.com/1932211/42322155-ab07b072-805b-11e8-85d5-9033c709eaa5.gif)


I have enabled by default, because I agree with @gayanper  comment https://github.com/angelozerr/jdt-codemining/issues/53#issuecomment-402507576

**Comment by nuessgens** [comment]
Very nice. Exactly what I was looking for. Many thanks!

**Comment by angelozerr** [comment]
Thanks for your feedback @nuessgens
