### ISSUE TITLE
Print margin is interrupted

### ISSUE THREAD

**Issue by Schalli1987** [angelozerr/jdt-codemining#59]
As shown in the attached image, the print margin is interrupted on the added "CodeMining lines".
This looks just broken ;-)

![image](https://user-images.githubusercontent.com/11866488/42320323-3fe97326-8055-11e8-9dba-2d98c329edc3.png)

**Comment by angelozerr** [comment]
Indeed it's ugly, but I have not found a clean solution for the moment. It's because line header mining (where 0 references is drawn) draw a blank rectangle because when line is selected (ex : public statc void main), the mining has blue color (the selected line).

I have tried to fix this problem but it requires changes of SWT TextLayout for all OS which is an hard thing. @mickaelistria here a new limitation of draw of mining in Platform Text

It's the same problem than https://github.com/angelozerr/jdt-codemining/issues/32

**Comment by gayanper** [comment]
@angelozerr  is there any plans to fix this in platform text ? a bug already reported ?

**Comment by angelozerr** [comment]
It's funny, I have created this bug now at https://bugs.eclipse.org/bugs/show_bug.cgi?id=538444

**Comment by angelozerr** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=538444 fixes the problem but give new problems like blue coloration of line header when line is selected, mark occurrences gray square which is too big.

So this issue will be fixed when https://bugs.eclipse.org/bugs/show_bug.cgi?id=539618 will be merged but it requires changes of SWT TextLayout https://bugs.eclipse.org/bugs/show_bug.cgi?id=539618 for each OS. I have doen it for Windows OD, but for Linux and Mac OS, I cannot test. Any help are welcome!

**Comment by gayanper** [comment]
For linux i can test it for you. Where can i dowload the SWT artifacts ?

**Comment by angelozerr** [comment]
> Where can i dowload the SWT artifacts ?

You cannot because for the moment gerrit patched are not merged. At first we need to fix https://bugs.eclipse.org/bugs/show_bug.cgi?id=539618

**Comment by angelozerr** [comment]
As https://bugs.eclipse.org/bugs/show_bug.cgi?id=539624 is merged in master, the future release of Eclipse (M3) will fix this issue.
